import { calculateMaturation } from "@/lib/maturation/calculations";
import type {
  AppState,
  Athlete,
  Club,
  Team,
  AnthropometricRecord,
  PerformanceEntry,
} from "@/lib/types";

export const demoClub: Club = {
  id: "club_arenas",
  name: "Arenas Performance Lab",
  region: "Madrid",
};

export const demoTeams: Team[] = [
  { id: "team_u14", clubId: demoClub.id, name: "U14 Boys", ageGroup: "U14" },
  { id: "team_u15g", clubId: demoClub.id, name: "U15 Girls", ageGroup: "U15" },
];

export const demoAthletes: Athlete[] = [
  {
    id: "ath_leo",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Leo Martin",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Winger",
    dob: "2012-02-14",
  },
  {
    id: "ath_hugo",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Hugo Sanz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Centre-back",
    dob: "2011-11-02",
  },
  {
    id: "ath_ines",
    clubId: demoClub.id,
    teamId: demoTeams[1].id,
    name: "Ines Vega",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Midfielder",
    dob: "2011-07-22",
  },
  {
    id: "ath_marta",
    clubId: demoClub.id,
    teamId: demoTeams[1].id,
    name: "Marta López",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Forward",
    dob: "2011-05-11",
  },
  {
    id: "ath_diego",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Diego Ruiz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Midfielder",
    dob: "2012-03-02",
  },
  {
    id: "ath_nora",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Nora Blanco",
    sex: "female",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Goalkeeper",
    dob: "2012-06-30",
  },
];

export const demoRecords: AnthropometricRecord[] = [
  {
    id: "rec_1",
    athleteId: "ath_leo",
    athleteName: "Leo Martin",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Winger",
    dob: "2012-02-14",
    dataCollectionDate: "2026-03-18",
    statureCm: 157.4,
    bodyMassKg: 46.3,
    sittingHeightCm: 81.5,
    motherHeightCm: 165,
    fatherHeightCm: 178,
    createdAt: "2026-03-18T10:30:00.000Z",
  },
  {
    id: "rec_2",
    athleteId: "ath_hugo",
    athleteName: "Hugo Sanz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Centre-back",
    dob: "2011-11-02",
    dataCollectionDate: "2026-03-18",
    statureCm: 168.9,
    bodyMassKg: 58.2,
    sittingHeightCm: 87.4,
    motherHeightCm: 164,
    fatherHeightCm: 181,
    createdAt: "2026-03-18T10:35:00.000Z",
  },
  {
    id: "rec_3",
    athleteId: "ath_ines",
    athleteName: "Ines Vega",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Midfielder",
    dob: "2011-07-22",
    dataCollectionDate: "2026-03-21",
    statureCm: 162.4,
    bodyMassKg: 51.1,
    sittingHeightCm: 84.2,
    motherHeightCm: 163,
    fatherHeightCm: 176,
    createdAt: "2026-03-21T17:00:00.000Z",
  },
  {
    id: "rec_4",
    athleteId: "ath_leo",
    athleteName: "Leo Martin",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Winger",
    dob: "2012-02-14",
    dataCollectionDate: "2026-01-11",
    statureCm: 154.8,
    bodyMassKg: 44.5,
    sittingHeightCm: 80.2,
    motherHeightCm: 165,
    fatherHeightCm: 178,
    createdAt: "2026-01-11T10:30:00.000Z",
  },
  {
    id: "rec_5",
    athleteId: "ath_marta",
    athleteName: "Marta López",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Forward",
    dob: "2011-05-11",
    dataCollectionDate: "2026-03-22",
    statureCm: 161.0,
    bodyMassKg: 50.4,
    sittingHeightCm: 83.1,
    motherHeightCm: 166,
    fatherHeightCm: 177,
    createdAt: "2026-03-22T09:15:00.000Z",
  },
  {
    id: "rec_6",
    athleteId: "ath_diego",
    athleteName: "Diego Ruiz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Midfielder",
    dob: "2012-03-02",
    dataCollectionDate: "2026-03-17",
    statureCm: 159.2,
    bodyMassKg: 47.8,
    sittingHeightCm: 81.8,
    motherHeightCm: 168,
    fatherHeightCm: 180,
    createdAt: "2026-03-17T10:20:00.000Z",
  },
  {
    id: "rec_7",
    athleteId: "ath_nora",
    athleteName: "Nora Blanco",
    sex: "female",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Goalkeeper",
    dob: "2012-06-30",
    dataCollectionDate: "2026-03-23",
    statureCm: 154.0,
    bodyMassKg: 44.1,
    sittingHeightCm: 78.9,
    motherHeightCm: 162,
    fatherHeightCm: 175,
    createdAt: "2026-03-23T08:45:00.000Z",
  },
];

export const demoPerformanceEntries: PerformanceEntry[] = [
  // --- Leo Martin (ath_leo) ---
  { id: "perf_1", athleteId: "ath_leo", athleteName: "Leo Martin", area: "physical", teamName: "U14 Boys", position: "Winger", testName: "10 m Sprint", unit: "s", value: 1.86, measurementDate: "2026-03-18", notes: "Electronic timing", createdAt: "2026-03-18T11:00:00.000Z" },
  { id: "perf_1b", athleteId: "ath_leo", athleteName: "Leo Martin", area: "physical", teamName: "U14 Boys", position: "Winger", testName: "30 m Sprint", unit: "s", value: 4.52, measurementDate: "2026-03-18", notes: "Electronic timing", createdAt: "2026-03-18T11:05:00.000Z" },
  { id: "perf_1c", athleteId: "ath_leo", athleteName: "Leo Martin", area: "physical", teamName: "U14 Boys", position: "Winger", testName: "CMJ", unit: "cm", value: 32.1, measurementDate: "2026-03-18", notes: "Optojump", createdAt: "2026-03-18T11:10:00.000Z" },
  { id: "perf_1d", athleteId: "ath_leo", athleteName: "Leo Martin", area: "physical", teamName: "U14 Boys", position: "Winger", testName: "Illinois Agility", unit: "s", value: 17.4, measurementDate: "2026-03-18", notes: "Cones drill", createdAt: "2026-03-18T11:20:00.000Z" },
  { id: "perf_1e", athleteId: "ath_leo", athleteName: "Leo Martin", area: "technicalTactical", teamName: "U14 Boys", position: "Winger", testName: "Dribbling Slalom", unit: "s", value: 12.3, measurementDate: "2026-03-18", notes: "8 conos", createdAt: "2026-03-18T11:30:00.000Z" },
  { id: "perf_1f", athleteId: "ath_leo", athleteName: "Leo Martin", area: "technicalTactical", teamName: "U14 Boys", position: "Winger", testName: "Shooting Speed", unit: "km/h", value: 78, measurementDate: "2026-03-18", notes: "Radar gun", createdAt: "2026-03-18T11:35:00.000Z" },
  { id: "perf_1g", athleteId: "ath_leo", athleteName: "Leo Martin", area: "psychological", teamName: "U14 Boys", position: "Winger", testName: "Confidence Score", unit: "/10", value: 8.5, measurementDate: "2026-03-18", notes: "Self-report", createdAt: "2026-03-18T11:40:00.000Z" },
  { id: "perf_1h", athleteId: "ath_leo", athleteName: "Leo Martin", area: "motorSkills", teamName: "U14 Boys", position: "Winger", testName: "Coordination Ladder", unit: "s", value: 9.8, measurementDate: "2026-03-18", notes: "4 patrones", createdAt: "2026-03-18T11:45:00.000Z" },

  // --- Hugo Sanz (ath_hugo) ---
  { id: "perf_2", athleteId: "ath_hugo", athleteName: "Hugo Sanz", area: "technicalTactical", teamName: "U14 Boys", position: "Centre-back", testName: "Video Tactical Decisions", unit: "/10", value: 7.8, measurementDate: "2026-03-19", notes: "Coach panel rating", createdAt: "2026-03-19T11:00:00.000Z" },
  { id: "perf_2b", athleteId: "ath_hugo", athleteName: "Hugo Sanz", area: "physical", teamName: "U14 Boys", position: "Centre-back", testName: "10 m Sprint", unit: "s", value: 1.95, measurementDate: "2026-03-19", notes: "Electronic timing", createdAt: "2026-03-19T11:05:00.000Z" },
  { id: "perf_2c", athleteId: "ath_hugo", athleteName: "Hugo Sanz", area: "physical", teamName: "U14 Boys", position: "Centre-back", testName: "CMJ", unit: "cm", value: 35.4, measurementDate: "2026-03-19", notes: "Optojump", createdAt: "2026-03-19T11:10:00.000Z" },
  { id: "perf_2d", athleteId: "ath_hugo", athleteName: "Hugo Sanz", area: "physical", teamName: "U14 Boys", position: "Centre-back", testName: "Handgrip Strength", unit: "kg", value: 28.5, measurementDate: "2026-03-19", notes: "Mano dominante", createdAt: "2026-03-19T11:15:00.000Z" },
  { id: "perf_2e", athleteId: "ath_hugo", athleteName: "Hugo Sanz", area: "technicalTactical", teamName: "U14 Boys", position: "Centre-back", testName: "Heading Accuracy", unit: "%", value: 75, measurementDate: "2026-03-19", notes: "8 de 10 centros", createdAt: "2026-03-19T11:20:00.000Z" },
  { id: "perf_2f", athleteId: "ath_hugo", athleteName: "Hugo Sanz", area: "psychological", teamName: "U14 Boys", position: "Centre-back", testName: "Leadership Rating", unit: "/10", value: 8.2, measurementDate: "2026-03-19", notes: "Coach assessment", createdAt: "2026-03-19T11:25:00.000Z" },
  { id: "perf_2g", athleteId: "ath_hugo", athleteName: "Hugo Sanz", area: "motorSkills", teamName: "U14 Boys", position: "Centre-back", testName: "Star Excursion Balance", unit: "cm", value: 68.3, measurementDate: "2026-03-19", notes: "Media 3 direcciones", createdAt: "2026-03-19T11:30:00.000Z" },

  // --- Ines Vega (ath_ines) ---
  { id: "perf_3", athleteId: "ath_ines", athleteName: "Ines Vega", area: "psychological", teamName: "U15 Girls", position: "Midfielder", testName: "Confidence Score", unit: "/10", value: 8.4, measurementDate: "2026-03-21", notes: "Self-report", createdAt: "2026-03-21T18:00:00.000Z" },
  { id: "perf_3b", athleteId: "ath_ines", athleteName: "Ines Vega", area: "physical", teamName: "U15 Girls", position: "Midfielder", testName: "Yo-Yo IR1", unit: "m", value: 1040, measurementDate: "2026-03-21", notes: "Nivel 16.3", createdAt: "2026-03-21T18:10:00.000Z" },
  { id: "perf_3c", athleteId: "ath_ines", athleteName: "Ines Vega", area: "physical", teamName: "U15 Girls", position: "Midfielder", testName: "CMJ", unit: "cm", value: 27.8, measurementDate: "2026-03-21", notes: "Optojump", createdAt: "2026-03-21T18:15:00.000Z" },
  { id: "perf_3d", athleteId: "ath_ines", athleteName: "Ines Vega", area: "technicalTactical", teamName: "U15 Girls", position: "Midfielder", testName: "Passing Accuracy", unit: "%", value: 88, measurementDate: "2026-03-21", notes: "10 pases a diana", createdAt: "2026-03-21T18:20:00.000Z" },
  { id: "perf_3e", athleteId: "ath_ines", athleteName: "Ines Vega", area: "technicalTactical", teamName: "U15 Girls", position: "Midfielder", testName: "First Touch Quality", unit: "/10", value: 7.9, measurementDate: "2026-03-21", notes: "Coach assessment", createdAt: "2026-03-21T18:25:00.000Z" },
  { id: "perf_3f", athleteId: "ath_ines", athleteName: "Ines Vega", area: "psychological", teamName: "U15 Girls", position: "Midfielder", testName: "Focus & Concentration", unit: "/10", value: 9.1, measurementDate: "2026-03-21", notes: "Stroop test adaptado", createdAt: "2026-03-21T18:30:00.000Z" },
  { id: "perf_3g", athleteId: "ath_ines", athleteName: "Ines Vega", area: "motorSkills", teamName: "U15 Girls", position: "Midfielder", testName: "Sit & Reach", unit: "cm", value: 34.5, measurementDate: "2026-03-21", notes: "Flexion lumbar", createdAt: "2026-03-21T18:35:00.000Z" },

  // --- Marta Lopez (ath_marta) ---
  { id: "perf_4", athleteId: "ath_marta", athleteName: "Marta López", area: "physical", teamName: "U15 Girls", position: "Forward", testName: "CMJ", unit: "cm", value: 29.3, measurementDate: "2026-03-22", notes: "Single-leg jump", createdAt: "2026-03-22T09:45:00.000Z" },
  { id: "perf_4b", athleteId: "ath_marta", athleteName: "Marta López", area: "physical", teamName: "U15 Girls", position: "Forward", testName: "30 m Sprint", unit: "s", value: 4.88, measurementDate: "2026-03-22", notes: "Electronic timing", createdAt: "2026-03-22T09:50:00.000Z" },
  { id: "perf_4c", athleteId: "ath_marta", athleteName: "Marta López", area: "technicalTactical", teamName: "U15 Girls", position: "Forward", testName: "Shooting Accuracy", unit: "%", value: 70, measurementDate: "2026-03-22", notes: "7 de 10 tiros a porteria", createdAt: "2026-03-22T09:55:00.000Z" },
  { id: "perf_4d", athleteId: "ath_marta", athleteName: "Marta López", area: "technicalTactical", teamName: "U15 Girls", position: "Forward", testName: "Shooting Speed", unit: "km/h", value: 72, measurementDate: "2026-03-22", notes: "Radar gun", createdAt: "2026-03-22T10:00:00.000Z" },
  { id: "perf_4e", athleteId: "ath_marta", athleteName: "Marta López", area: "technicalTactical", teamName: "U15 Girls", position: "Forward", testName: "Ball Control (Juggling)", unit: "reps", value: 54, measurementDate: "2026-03-22", notes: "Ambos pies", createdAt: "2026-03-22T10:05:00.000Z" },
  { id: "perf_4f", athleteId: "ath_marta", athleteName: "Marta López", area: "psychological", teamName: "U15 Girls", position: "Forward", testName: "Resilience Score", unit: "/10", value: 7.5, measurementDate: "2026-03-22", notes: "Cuestionario adaptado", createdAt: "2026-03-22T10:10:00.000Z" },
  { id: "perf_4g", athleteId: "ath_marta", athleteName: "Marta López", area: "motorSkills", teamName: "U15 Girls", position: "Forward", testName: "Single-Leg Hop", unit: "cm", value: 142, measurementDate: "2026-03-22", notes: "Pierna dominante", createdAt: "2026-03-22T10:15:00.000Z" },

  // --- Diego Ruiz (ath_diego) ---
  { id: "perf_5", athleteId: "ath_diego", athleteName: "Diego Ruiz", area: "technicalTactical", teamName: "U14 Boys", position: "Midfielder", testName: "Passing Accuracy", unit: "%", value: 87.5, measurementDate: "2026-03-17", notes: "10 passes target drill", createdAt: "2026-03-17T11:10:00.000Z" },
  { id: "perf_5b", athleteId: "ath_diego", athleteName: "Diego Ruiz", area: "physical", teamName: "U14 Boys", position: "Midfielder", testName: "Yo-Yo IR1", unit: "m", value: 1280, measurementDate: "2026-03-17", notes: "Nivel 17.4", createdAt: "2026-03-17T11:15:00.000Z" },
  { id: "perf_5c", athleteId: "ath_diego", athleteName: "Diego Ruiz", area: "physical", teamName: "U14 Boys", position: "Midfielder", testName: "505 COD", unit: "s", value: 2.38, measurementDate: "2026-03-17", notes: "Pie derecho", createdAt: "2026-03-17T11:20:00.000Z" },
  { id: "perf_5d", athleteId: "ath_diego", athleteName: "Diego Ruiz", area: "technicalTactical", teamName: "U14 Boys", position: "Midfielder", testName: "Positional Awareness", unit: "/10", value: 8.6, measurementDate: "2026-03-17", notes: "GPS + video analysis", createdAt: "2026-03-17T11:25:00.000Z" },
  { id: "perf_5e", athleteId: "ath_diego", athleteName: "Diego Ruiz", area: "psychological", teamName: "U14 Boys", position: "Midfielder", testName: "Teamwork & Communication", unit: "/10", value: 9.2, measurementDate: "2026-03-17", notes: "Peer assessment", createdAt: "2026-03-17T11:30:00.000Z" },
  { id: "perf_5f", athleteId: "ath_diego", athleteName: "Diego Ruiz", area: "psychological", teamName: "U14 Boys", position: "Midfielder", testName: "Motivation Score", unit: "/10", value: 8.8, measurementDate: "2026-03-17", notes: "Cuestionario SMS-II", createdAt: "2026-03-17T11:35:00.000Z" },
  { id: "perf_5g", athleteId: "ath_diego", athleteName: "Diego Ruiz", area: "motorSkills", teamName: "U14 Boys", position: "Midfielder", testName: "T-Test (Lateral Agility)", unit: "s", value: 10.9, measurementDate: "2026-03-17", notes: "Conos a 5 m", createdAt: "2026-03-17T11:40:00.000Z" },

  // --- Nora Blanco (ath_nora) ---
  { id: "perf_6", athleteId: "ath_nora", athleteName: "Nora Blanco", area: "psychological", teamName: "U14 Boys", position: "Goalkeeper", testName: "Coachability Rating", unit: "/10", value: 9.0, measurementDate: "2026-03-23", notes: "Muy receptiva", createdAt: "2026-03-23T09:00:00.000Z" },
  { id: "perf_6b", athleteId: "ath_nora", athleteName: "Nora Blanco", area: "physical", teamName: "U14 Boys", position: "Goalkeeper", testName: "SJ (Squat Jump)", unit: "cm", value: 24.2, measurementDate: "2026-03-23", notes: "Sin contramovimiento", createdAt: "2026-03-23T09:10:00.000Z" },
  { id: "perf_6c", athleteId: "ath_nora", athleteName: "Nora Blanco", area: "physical", teamName: "U14 Boys", position: "Goalkeeper", testName: "Handgrip Strength", unit: "kg", value: 22.1, measurementDate: "2026-03-23", notes: "Mano dominante", createdAt: "2026-03-23T09:15:00.000Z" },
  { id: "perf_6d", athleteId: "ath_nora", athleteName: "Nora Blanco", area: "technicalTactical", teamName: "U14 Boys", position: "Goalkeeper", testName: "Small-Sided Decision Rating", unit: "/10", value: 7.5, measurementDate: "2026-03-23", notes: "Juego reducido 4v4", createdAt: "2026-03-23T09:20:00.000Z" },
  { id: "perf_6e", athleteId: "ath_nora", athleteName: "Nora Blanco", area: "psychological", teamName: "U14 Boys", position: "Goalkeeper", testName: "Focus & Concentration", unit: "/10", value: 8.7, measurementDate: "2026-03-23", notes: "Test atencional", createdAt: "2026-03-23T09:25:00.000Z" },
  { id: "perf_6f", athleteId: "ath_nora", athleteName: "Nora Blanco", area: "motorSkills", teamName: "U14 Boys", position: "Goalkeeper", testName: "Ruler Drop Test", unit: "cm", value: 14.2, measurementDate: "2026-03-23", notes: "Mejor de 3 intentos", createdAt: "2026-03-23T09:30:00.000Z" },
  { id: "perf_6g", athleteId: "ath_nora", athleteName: "Nora Blanco", area: "motorSkills", teamName: "U14 Boys", position: "Goalkeeper", testName: "Star Excursion Balance", unit: "cm", value: 72.1, measurementDate: "2026-03-23", notes: "Media 3 direcciones", createdAt: "2026-03-23T09:35:00.000Z" },
];

export const demoState: AppState = {
  club: demoClub,
  teams: demoTeams,
  athletes: demoAthletes,
  records: demoRecords,
  performanceEntries: demoPerformanceEntries,
  trainingLoadEntries: [],
  gpsSessions: [],
  performanceDefinitions: [
    // Physical tests (10)
    { id: "pdef-10m-sprint", name: "10 m Sprint", nameKey: "datahub.presetName.sprint10m", descriptionKey: "datahub.presetSprintDesc", area: "physical", unit: "s", attempts: 2, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Velocidad en sprint corto. Mide la aceleracion inicial, fundamental en acciones explosivas del futbol." },
    { id: "pdef-30m-sprint", name: "30 m Sprint", nameKey: "datahub.presetName.sprint30m", descriptionKey: "datahub.preset30mSprintDesc", area: "physical", unit: "s", attempts: 2, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Velocidad en sprint lanzado. Evalua la velocidad maxima del jugador." },
    { id: "pdef-cmj", name: "CMJ", nameKey: "datahub.presetName.cmj", descriptionKey: "datahub.presetCmjDesc", area: "physical", unit: "cm", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Counter Movement Jump. Mide la potencia explosiva del tren inferior con contramovimiento." },
    { id: "pdef-sj", name: "SJ (Squat Jump)", nameKey: "datahub.presetName.sj", descriptionKey: "datahub.presetSjDesc", area: "physical", unit: "cm", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Squat Jump. Mide la fuerza explosiva concentrica sin ciclo estiramiento-acortamiento." },
    { id: "pdef-yoyo", name: "Yo-Yo IR1", nameKey: "datahub.presetName.yoyo", descriptionKey: "datahub.presetYoyoDesc", area: "physical", unit: "m", attempts: 1, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Test de resistencia intermitente. Evalua la capacidad aerobica con pausa activa, similar a las demandas del futbol." },
    { id: "pdef-505", name: "505 COD", nameKey: "datahub.presetName.cod505", descriptionKey: "datahub.presetCodDesc", area: "physical", unit: "s", attempts: 2, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Change of Direction test. Mide la agilidad y capacidad de cambio de direccion a 180°." },
    { id: "pdef-illinois", name: "Illinois Agility", nameKey: "datahub.presetName.illinois", descriptionKey: "datahub.presetIllinoisDesc", area: "physical", unit: "s", attempts: 2, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Test de agilidad con cambios de direccion multiples. Evalua la movilidad y velocidad con giros." },
    { id: "pdef-rsa", name: "RSA (Repeated Sprint)", nameKey: "datahub.presetName.rsa", descriptionKey: "datahub.presetRsaDesc", area: "physical", unit: "s", attempts: 1, isRating: false, scoringStrategy: "average", interpretation: "lower_better", description: "Repeated Sprint Ability. Media de 6x30m con 20s de descanso. Evalua la resistencia a sprints repetidos." },
    { id: "pdef-handgrip", name: "Handgrip Strength", nameKey: "datahub.presetName.handgrip", descriptionKey: "datahub.presetHandgripDesc", area: "physical", unit: "kg", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Fuerza de agarre con dinamometro. Indicador de fuerza general del tren superior." },
    { id: "pdef-wall-sit", name: "Wall Sit Test", nameKey: "datahub.presetName.wallSit", descriptionKey: "datahub.presetWallSitDesc", area: "physical", unit: "s", attempts: 1, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Test de resistencia isometrica de cuadriceps. Mide el tiempo manteniendo posicion sentado en pared." },

    // Technical-Tactical tests (10)
    { id: "pdef-passing", name: "Passing Accuracy", nameKey: "datahub.presetName.passing", descriptionKey: "datahub.presetPassingDesc", area: "technicalTactical", unit: "%", attempts: 1, isRating: false, scoringStrategy: "average", interpretation: "higher_better", description: "Precision de pase sobre diana. 10 pases a distintas distancias y angulos. Evalua la tecnica de pase." },
    { id: "pdef-shooting-acc", name: "Shooting Accuracy", nameKey: "datahub.presetName.shootingAcc", descriptionKey: "datahub.presetShootingAccDesc", area: "technicalTactical", unit: "%", attempts: 1, isRating: false, scoringStrategy: "average", interpretation: "higher_better", description: "Precision de tiro. Porcentaje de acierto sobre 10 disparos a zonas especificas de la porteria." },
    { id: "pdef-shooting-speed", name: "Shooting Speed", nameKey: "datahub.presetName.shootingSpeed", descriptionKey: "datahub.presetShootingSpeedDesc", area: "technicalTactical", unit: "km/h", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Velocidad de disparo medida con radar. Evalua la potencia de golpeo." },
    { id: "pdef-dribbling", name: "Dribbling Slalom", nameKey: "datahub.presetName.dribbling", descriptionKey: "datahub.presetDribblingDesc", area: "technicalTactical", unit: "s", attempts: 2, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Slalom de conduccion entre 8 conos. Evalua el control de balon a velocidad con cambios de direccion." },
    { id: "pdef-juggling", name: "Ball Control (Juggling)", nameKey: "datahub.presetName.juggling", descriptionKey: "datahub.presetJugglingDesc", area: "technicalTactical", unit: "reps", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Dominio de balon (toques). Maximo numero de toques consecutivos sin que caiga el balon." },
    { id: "pdef-first-touch", name: "First Touch Quality", nameKey: "datahub.presetName.firstTouch", descriptionKey: "datahub.presetFirstTouchDesc", area: "technicalTactical", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Calidad del primer toque evaluada por el cuerpo tecnico en situacion de juego real." },
    { id: "pdef-heading", name: "Heading Accuracy", nameKey: "datahub.presetName.heading", descriptionKey: "datahub.presetHeadingDesc", area: "technicalTactical", unit: "%", attempts: 1, isRating: false, scoringStrategy: "average", interpretation: "higher_better", description: "Precision de cabeceo sobre 10 centros. Evalua la tecnica de juego aereo." },
    { id: "pdef-video-decision", name: "Video Tactical Decisions", nameKey: "datahub.presetName.videoDecision", descriptionKey: "datahub.presetVideoDecisionDesc", area: "technicalTactical", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Evaluacion de toma de decisiones tacticas mediante analisis de video." },
    { id: "pdef-ssg-decision", name: "Small-Sided Decision Rating", nameKey: "datahub.presetName.ssgDecision", descriptionKey: "datahub.presetSsgDecisionDesc", area: "technicalTactical", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Calificacion de decisiones en juegos reducidos (3v3, 4v4) evaluada por cuerpo tecnico." },
    { id: "pdef-positional", name: "Positional Awareness", nameKey: "datahub.presetName.positional", descriptionKey: "datahub.presetPositionalDesc", area: "technicalTactical", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Evaluacion del posicionamiento tactico usando GPS y video. Ocupacion de espacios e inteligencia posicional." },

    // Psychological tests (8)
    { id: "pdef-confidence", name: "Confidence Score", nameKey: "datahub.presetName.confidence", descriptionKey: "datahub.presetConfidenceDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Nivel de autoconfianza del jugador medido mediante cuestionario validado (CSAI-2R adaptado)." },
    { id: "pdef-motivation", name: "Motivation Score", nameKey: "datahub.presetName.motivation", descriptionKey: "datahub.presetMotivationDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Motivacion intrinseca evaluada con cuestionario SMS-II. Mide el compromiso autonomo con la practica." },
    { id: "pdef-anxiety", name: "Competitive Anxiety", nameKey: "datahub.presetName.anxiety", descriptionKey: "datahub.presetAnxietyDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Control de ansiedad competitiva. Puntuacion invertida: mayor puntuacion = mejor gestion de la ansiedad." },
    { id: "pdef-coachability", name: "Coachability Rating", nameKey: "datahub.presetName.coachability", descriptionKey: "datahub.presetCoachabilityDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Capacidad de aprendizaje y receptividad al feedback del cuerpo tecnico." },
    { id: "pdef-resilience", name: "Resilience Score", nameKey: "datahub.presetName.resilience", descriptionKey: "datahub.presetResilienceDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Capacidad de recuperacion ante adversidades. Evalua la fortaleza mental y persistencia." },
    { id: "pdef-focus", name: "Focus & Concentration", nameKey: "datahub.presetName.focus", descriptionKey: "datahub.presetFocusDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Capacidad de atencion y concentracion durante tareas complejas. Test atencional adaptado al deporte." },
    { id: "pdef-leadership", name: "Leadership Rating", nameKey: "datahub.presetName.leadership", descriptionKey: "datahub.presetLeadershipDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Capacidad de liderazgo evaluada por cuerpo tecnico y companeros (evaluacion 360)." },
    { id: "pdef-teamwork", name: "Teamwork & Communication", nameKey: "datahub.presetName.teamwork", descriptionKey: "datahub.presetTeamworkDesc", area: "psychological", unit: "/10", attempts: 1, isRating: true, scoringStrategy: "average", interpretation: "higher_better", description: "Habilidades de trabajo en equipo y comunicacion en campo. Peer-assessment." },

    // Motor Skills tests (6)
    { id: "pdef-star-balance", name: "Star Excursion Balance", nameKey: "datahub.presetName.starBalance", descriptionKey: "datahub.presetStarBalanceDesc", area: "motorSkills", unit: "cm", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Test de equilibrio dinamico unipodal. Media de alcance en 3 direcciones. Indicador de estabilidad y riesgo de lesion." },
    { id: "pdef-coord-ladder", name: "Coordination Ladder", nameKey: "datahub.presetName.coordLadder", descriptionKey: "datahub.presetCoordLadderDesc", area: "motorSkills", unit: "s", attempts: 2, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Escalera de coordinacion con 4 patrones predefinidos. Evalua velocidad de pies y coordinacion motora." },
    { id: "pdef-ruler-drop", name: "Ruler Drop Test", nameKey: "datahub.presetName.rulerDrop", descriptionKey: "datahub.presetRulerDropDesc", area: "motorSkills", unit: "cm", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Test de tiempo de reaccion visual. Distancia de caida en centimetros (menor = mejor reaccion)." },
    { id: "pdef-sit-reach", name: "Sit & Reach", nameKey: "datahub.presetName.sitReach", descriptionKey: "datahub.presetSitReachDesc", area: "motorSkills", unit: "cm", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Flexibilidad de cadena posterior (isquiotibiales y lumbar). Test clasico de flexion sentado." },
    { id: "pdef-single-leg-hop", name: "Single-Leg Hop", nameKey: "datahub.presetName.singleLegHop", descriptionKey: "datahub.presetSingleLegHopDesc", area: "motorSkills", unit: "cm", attempts: 3, isRating: false, scoringStrategy: "best", interpretation: "higher_better", description: "Salto horizontal unipodal. Evalua la potencia unilateral y simetria entre piernas." },
    { id: "pdef-ttest", name: "T-Test (Lateral Agility)", nameKey: "datahub.presetName.ttest", descriptionKey: "datahub.presetTTestDesc", area: "motorSkills", unit: "s", attempts: 2, isRating: false, scoringStrategy: "best", interpretation: "lower_better", description: "Agilidad lateral en forma de T. Incluye desplazamientos laterales, frontales y hacia atras." },
  ],
  preferences: {
    locale: "es",
  },
  currentUserRole: "admin",
  currentUserTeamIds: [],
  currentUserPermissions: {
    canEditAthletes: true,
    canEditAnthropometry: true,
    canEditPerformance: true,
    canEditTrainingLoad: true,
  },
  clubUsers: [
    {
      id: "user-admin-1",
      clubId: "demo-club",
      name: "Carlos Martínez",
      email: "carlos@academiasevilla.es",
      role: "admin",
      assignedTeamIds: [],
      permissions: { canEditAthletes: true, canEditAnthropometry: true, canEditPerformance: true, canEditTrainingLoad: true },
      createdAt: "2024-09-01T08:00:00.000Z",
    },
    {
      id: "user-staff-1",
      clubId: "demo-club",
      name: "Marta García",
      email: "marta@academiasevilla.es",
      role: "user",
      assignedTeamIds: ["team-u10", "team-u12"],
      permissions: { canEditAthletes: true, canEditAnthropometry: true, canEditPerformance: false, canEditTrainingLoad: false },
      createdAt: "2024-09-15T10:30:00.000Z",
    },
    {
      id: "user-staff-2",
      clubId: "demo-club",
      name: "Alejandro Ruiz",
      email: "alejandro@academiasevilla.es",
      role: "user",
      assignedTeamIds: ["team-u14"],
      permissions: { canEditAthletes: false, canEditAnthropometry: true, canEditPerformance: true, canEditTrainingLoad: true },
      createdAt: "2025-01-10T09:00:00.000Z",
    },
  ],
};

export const demoAssessments = demoRecords.map((record) => calculateMaturation(record));